# Generated by Django 2.2.5 on 2019-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('min_price', models.FloatField(help_text='Set the minimum price')),
                ('deadline', models.DateTimeField(help_text='Deadline for bidding')),
            ],
        ),
    ]
