# Generated by Django 2.2.5 on 2019-11-07 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 19, 52, 32, 682125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='min_price',
            field=models.FloatField(max_length=200),
        ),
    ]
