# Generated by Django 2.2.5 on 2019-11-07 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191107_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 21, 11, 5, 451043, tzinfo=utc)),
        ),
    ]
