# Generated by Django 2.2.5 on 2019-11-08 22:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20191108_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 22, 42, 25, 939628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 22, 42, 25, 939628, tzinfo=utc)),
        ),
    ]
