# Generated by Django 2.2.5 on 2019-11-08 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20191109_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 23, 41, 5, 60897, tzinfo=utc)),
        ),
    ]
