# Generated by Django 2.2.5 on 2019-11-09 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20191109_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 21, 42, 27, 731607, tzinfo=utc)),
        ),
    ]
