# Generated by Django 2.2.5 on 2019-11-11 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20191111_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 7, 59, 37, 166772, tzinfo=utc)),
        ),
    ]
