# Generated by Django 2.2.5 on 2019-11-09 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20191109_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 22, 30, 11, 522699, tzinfo=utc)),
        ),
    ]
