# Generated by Django 2.2.5 on 2019-11-11 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20191111_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 19, 47, 58, 668105, tzinfo=utc)),
        ),
    ]
